modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory (35 is current forge version)
issueTrackerURL="https://github.com/Squidsword/OresAboveDiamonds/issues"
license="MIT"

[[mods]] #mandatory
modId="oresabovediamonds" #mandatory
version="6.2.0" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/ores-above-diamonds" #optional
displayName="Ores Above Diamonds" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Squidsword/OresAboveDiamonds/1.16.4/update.json" #optional
logoFile="oresabovediamonds_logo.png" #optional
# A text field displayed in the mod UI
authors="§dSquidsword" #optional
credits="Special thanks to §6CriativeMan1§r for the making the art for this mod!"
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds the §dAmethyst§r and §5Black Opal§r which are respectively §d3x§r and §59x§r rarer than diamonds.
Both have its own set of balanced armors and tools.

It's recommended to download Overloaded Armor Bar along with this mod.
https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar/

The mod doesn't have built in retrogen support. This means that ores will not spawn in already loaded chunks. Venture far into unexplored lands to have a chance at finding them.
'''
# Here's another dependency

[[dependencies.oresabovediamonds]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.0,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.oresabovediamonds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
